version: '2'
services:
    jhipsternudes-app:
        image: jhipsternudes
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsternudes-mysql:3306/jhipsternudes?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsternudes-mysql:
        extends:
            file: mysql.yml
            service: jhipsternudes-mysql
